# Generated by Django 4.2.1 on 2023-05-12 16:05

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(default=users.models.get_default_mesa, on_delete=django.db.models.deletion.CASCADE, to='users.mesa'),
        ),
    ]
